# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
#      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.2'  # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        files: "^frontend/"
        exclude: "^frontend/src/lib/i18n/locales/"
        additional_dependencies:
          - "prettier-plugin-svelte@latest"
          - "prettier@latest"
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        # flake8 is passed in all tracked python files
        # so --exclude in .flake8 does not work
        exclude: ^migrations/versions/
