# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "[CI] Frontend / Lint"

on:
  push:
    branches: [ master ]
    paths:
      - "frontend/**"
  workflow_dispatch:
  pull_request:

jobs:
  frontend_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.14.0
          working-directory: ./frontend

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          pnpm install

      - name: Lint
        working-directory: ./frontend
        run: |
          pnpm run lint-without-format-checking
